#_StudyParameters__dir_path = "/home/takodev/bhceye/biohci-project/Resources/CTS_5taps_per_button"
#resource_path = "/home/denisa/GitHub/BioHCI Project/Resources/CTS_Keyboard"
resource_path = "CTS_Keyboard"
study_name = "CTS_Keyboard"
sensor_name = "Capacitor"
file_format = ".csv"
relevant_columns = "[0:102]"
column_names = "None"
start_row = 0
cat_names = "dir"
num_subj = 3
labels_col = "None"
plot_labels = ["Voltage Frequency Gain", "Time"]
standardize = false
compute_fft = false
sampling_freq = "None"
nfft = "None"
chunk_instances = true
samples_per_chunk = 250
interval_overlap = false
construct_features = true
feature_window = 250
feature_overlap = false
num_folds = 3
num_threads = 32
neural_net = true
