#cv_resource_path = "CTS_4Electrodes"
#test_resource_path = "None"
cv_resource_path = "CTS_4Electrodes/Lev_Data"
test_resource_path = "CTS_4Electrodes/Rich_Data"
study_name = "CTS_4Electrodes"
sensor_name = "Capacitor"
file_format = ".csv"
relevant_columns = "[0:4]"
column_names = "None"
start_row = 0
cat_names = "dir"
num_subj = 1
labels_col = "None"
plot_labels = ["Voltage Frequency Gains", "Time"]
standardize = false
compute_fft = false
sampling_freq = false
nfft = false
chunk_instances = true
samples_per_chunk = 250
interval_overlap = false
construct_features = true
feature_window = 250
feature_overlap = false
num_folds = 10
num_threads = 4
neural_net = true
classification = true
