#_StudyParameters__dir_path = "/home/takodev/bhceye/biohci-project/Resources/CTS_5taps_per_button"
#_StudyParameters__dir_path = "/home/denisa/GitHub/BioHCI-Project/Resources/CTS_5taps_per_button"
resource_path = "CTS_5taps_per_button"
study_name = "CTS_5taps_per_button"
sensor_name = "Capacitor"
file_format = ".csv"
relevant_columns = [1, 2]
column_names = ["A", "B"]
start_row = 0
cat_names = "dir"
num_subj = 1
labels_col = "None"
plot_labels = ["Voltage Frequency Gain", "Time"]
standardize = false
compute_fft = false
sampling_freq = false
nfft = false
chunk_instances = true
samples_per_chunk = 1000
interval_overlap = false
construct_features = true
feature_window = 1000
feature_overlap = false
num_folds = 2
num_threads = 12
neural_net = true
classification = true
