cv_resource_path = "CTS_UbiComp2020/tmp/tmp_train"
test_resource_path = "CTS_UbiComp2020/tmp/tmp_val_test_1"
study_name = "CTS_UbiComp2020_tmp"
sensor_name = "Capacitor"
file_format = ".csv"
relevant_columns = "[0:192]"
column_names = "None"
start_row = 0
cat_names = "dir"
num_subj = 7
labels_col = "None"
plot_labels = ["Voltage Frequency Gain", "Time"]
standardize = false
compute_fft = false
sampling_freq = false
nfft = false
chunk_instances = true
samples_per_chunk = 250
interval_overlap = false
construct_features = true
feature_window = 250
feature_overlap = false
num_folds = 3
num_threads = 12
neural_net = true
classification = true
