#_StudyParameters__dir_path = "/home/takodev/bhceye/biohci-project/Resources/CTS_5taps_per_button"
_StudyParameters__dir_path = "/home/denisa/GitHub/BioHCI Project/Resources/CTS_5taps_per_button"
_StudyParameters__study_name = "CTS_5taps_per_button"
_StudyParameters__sensor_name = "Capacitor"
_StudyParameters__file_format = ".csv"
_StudyParameters__relevant_columns = [1, 2]
_StudyParameters__column_names = ["A", "B"]
_StudyParameters__start_row = 0
_StudyParameters__cat_names = "dir"
_StudyParameters__num_subj = 1
_StudyParameters__labels_col = "None"
_StudyParameters__plot_labels = ["Voltage Frequency Gain", "Time"]
_StudyParameters__standardize = false
_StudyParameters__compute_fft = false
_StudyParameters__sampling_freq = false
_StudyParameters__nfft = false
_StudyParameters__chunk_instances = true
_StudyParameters__samples_per_chunk = 1000
_StudyParameters__interval_overlap = false
_StudyParameters__construct_features = true
_StudyParameters__feature_window = 1000
_StudyParameters__feature_overlap = false
_StudyParameters__num_folds = 5
_StudyParameters__num_threads = "None"
_StudyParameters__neural_net = "None"
