#resource_path = "CTS_CHI2020/tmp/tmp_val_test_1"
resource_path = "CTS_CHI2020/test_basic"
#resource_path = "CTS_CHI2020/test_fluorescent_light"
#resource_path = "CTS_CHI2020/test_stretch"
study_name = "CTS_CHI2020"
sensor_name = "Capacitor"
file_format = ".csv"
relevant_columns = "[0:192]"
#relevant_columns = [143, 144]
#relevant_columns = [0, 1]
column_names = "None"
start_row = 0
cat_names = "dir"
num_subj = 4
labels_col = "None"
plot_labels = ["Voltage Frequency Gain", "Time"]
standardize = false
compute_fft = false
sampling_freq = false
nfft = false
chunk_instances = true
samples_per_chunk = 250
interval_overlap = false
construct_features = true
feature_window = 250
feature_overlap = false
num_folds = 2
num_threads = 4
neural_net = true
classification = true
