cv_resource_path = "CTS_volume_swipe/test"
study_name = "CTS_volume_swipe"
sensor_name = "Capacitor"
file_format = ".csv"
relevant_columns = "[0:4]"
column_names = "None"
start_row = 0
cat_names = "dir"
num_subj = 5
labels_col = "None"
plot_labels = ["Voltage Frequency Gains", "Time"]
standardize = false
compute_fft = false
sampling_freq = false
nfft = false
chunk_instances = true
samples_per_chunk = 250
interval_overlap = false
construct_features = true
feature_window = 250
feature_overlap = false
num_folds = 5
num_threads = 4
neural_net = true
classification = true
