_StudyParameters__dir_path = "None"
_StudyParameters__study_name = "None"
_StudyParameters__sensor_name = "None"
_StudyParameters__file_format = "None"
_StudyParameters__relevant_columns = "None"
_StudyParameters__start_row = "None"
_StudyParameters__num_subj = "None"
_StudyParameters__labels_col = "None"
_StudyParameters__standardize = "None"
_StudyParameters__samples_per_chunk = "None"
_StudyParameters__interval_overlap = "None"
_StudyParameters__construct_features = "None"
_StudyParameters__feature_window = "None"
_StudyParameters__num_folds = "None"
_StudyParameters__num_threads = "None"
_StudyParameters__neural_net = "None"
